-- WITH t_0 as (
SELECT
    cast("id" as int),
    trim("Name") as name,
    cast("Release Date" as date) as release_date,
    -- year("Release date") as year,
    substring("IMDB URL", 19) as imdb_url,
    cast(cast("Action" as int) as boolean) as action,
    cast(cast("adventure" as int) as boolean),
    cast(cast("animation" as int) as boolean),
    cast(cast("Children's" as int) as boolean) as childrens,
    cast(cast("comedy" as int) as boolean),
    cast(cast("crime" as int) as boolean),
    cast(cast("documentary" as int) as boolean),
    cast(cast("drama" as int) as boolean),
    cast(cast("fantasy" as int) as boolean),
    cast(cast("Film-Noir" as int) as boolean) as film_noir,
    cast(cast("horror" as int) as boolean),
    cast(cast("musical" as int) as boolean),
    cast(cast("mystery" as int) as boolean),
    cast(cast("romance" as int) as boolean),
    cast(cast("Sci-Fi" as int) as boolean) as sci_fi,
    cast(cast("thriller" as int) as boolean),
    cast(cast("war" as int) as boolean),
    cast(cast("western" as int) as boolean)
FROM {{ source("recommender_system_raw", "movies_raw") }}
